"""Canonical English contracts for structured data produced by LLM services."""

KEY_ALIASES = {
    "entrada_invalida": "invalid_input",
    "motivo_entrada_invalida": "invalid_input_reason",
    "documento_e_vaga": "is_job_posting",
    "candidato": "candidate",
    "nome": "name",
    "cargo_desejado": "desired_job_title",
    "senioridade_percebida_pelo_llm": "llm_estimated_seniority",
    "localizacao": "location",
    "skills_tecnicas": "technical_skills",
    "categoria": "category",
    "nivel_confianca": "confidence_level",
    "principais_areas_atuacao": "primary_areas",
    "stack_tecnologica": "technology_stack",
    "experiencias_profissionais": "professional_experience",
    "empresa": "company",
    "cargo": "job_title",
    "periodo": "period",
    "duracao_meses": "duration_months",
    "resumo": "summary",
    "conta_como_experiencia_tecnica": "counts_as_technical_experience",
    "formacao_academica": "education",
    "curso": "course",
    "instituicao": "institution",
    "nivel": "level",
    "concluido": "completed",
    "certificacoes": "certifications",
    "anos_experiencia_tecnica": "technical_experience_years",
    "senioridade_estimada_por_metricas": "calculated_seniority",
    "vaga": "job",
    "titulo": "title",
    "modelo_trabalho": "work_model",
    "requisitos_obrigatorios": "required_skills",
    "requisitos_desejaveis": "preferred_skills",
    "requisitos_elegibilidade": "eligibility_requirements",
    "responsabilidades": "responsibilities",
    "tecnologias_mencionadas": "mentioned_technologies",
    "senioridade_esperada": "expected_seniority",
    "area_vaga": "job_area",
    "confianca_geral_analise": "overall_confidence",
    "campos_nao_encontrados": "missing_fields",
    "score_compatibilidade": "compatibility_score",
    "skills_compativeis": "matching_skills",
    "skills_faltantes": "missing_skills",
    "pontos_fortes": "strengths",
    "pontos_melhoria": "improvement_areas",
    "senioridade_compativel": "seniority_compatible",
    "explicacao_score": "score_explanation",
    "recomendacoes": "recommendations",
    "desafio": "challenge",
    "area_tecnica": "technical_area",
    "nivel_dificuldade_geral": "overall_difficulty",
    "total_perguntas": "total_questions",
    "blocos": "blocks",
    "bloco_id": "block_id",
    "topico": "topic",
    "perguntas": "questions",
    "enunciado": "prompt",
    "dificuldade": "difficulty",
    "criterio_avaliacao": "evaluation_criteria",
    "skills_avaliadas": "evaluated_skills",
    "resposta": "answer",
    "avaliacao": "evaluation",
    "conhecimento_tecnico": "technical_knowledge",
    "clareza_explicacao": "explanation_clarity",
    "profundidade_conceitual": "conceptual_depth",
    "evidencias": "evidence",
    "pontos_fracos": "weaknesses",
    "confianca_avaliacao": "evaluation_confidence",
    "talent_passport_final": "talent_passport",
    "resumo_profissional": "professional_summary",
    "nivel_geral": "overall_level",
    "competencias": "competencies",
    "areas_desenvolvimento": "development_areas",
    "profissoes_sugeridas": "suggested_roles",
    "match_percentual": "match_percentage",
    "justificativa": "rationale",
    "recursos_sugeridos": "suggested_resources",
    "skill_relacionada": "related_skill",
    "tipo": "type",
    "sugestao": "suggestion",
    "confianca_geral": "overall_confidence",
    "nivel_proficiencia": "proficiency_level",
    "match_confianca": "confidence_match",
    "introducao": "introduction",
    "itens": "items",
    "posicao": "position",
    "motivacao": "motivation",
    "tipo_recurso": "resource_type",
    "sugestao_recurso": "resource_suggestion",
    "score_teste": "overall_score",
    "compatibilidade_vaga": "job_compatibility",
    "desempenho_tecnico": "technical_performance",
    "melhor_area": "best_area",
    "desempenho_por_area": "performance_by_area",
    "desempenho_por_skill": "performance_by_skill",
    "melhores_skills": "top_skills",
    "feedback_resumo": "summary_feedback",
}

VALUE_ALIASES = {
    "pleno": "mid_level",
    "especialista": "expert",
    "iniciante": "beginner",
    "intermediario": "intermediate",
    "avancado": "advanced",
    "facil": "easy",
    "medio": "medium",
    "dificil": "hard",
    "presencial": "onsite",
    "remoto": "remote",
    "hibrido": "hybrid",
    "linguagem": "language",
    "ferramenta": "tool",
    "banco_de_dados": "database",
    "metodologia_ou_conceito": "methodology_or_concept",
    "outro": "other",
    "tecnico": "technical",
    "graduacao": "undergraduate",
    "pos": "postgraduate",
    "mestrado": "masters",
    "doutorado": "doctorate",
    "certificacao": "certification",
    "documentacao": "documentation",
    "pratica_projeto": "project_practice",
}


def canonicalize_json(value):
    """Recursively translate known legacy keys and enum values to English."""
    if isinstance(value, dict):
        return {
            KEY_ALIASES.get(key, key): canonicalize_json(item)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [canonicalize_json(item) for item in value]
    if isinstance(value, str):
        return VALUE_ALIASES.get(value, value)
    return value
